version: "3.3"

# Configuração das redes entre os containers
networks:
  traefik:
    name: traefik
    external: false
  bridge:
    name: bridge
    external: true


services:

  traefik-hub:
    image: ghcr.io/traefik/hub-agent-traefik
    container_name: traefikhub-agent
    restart: "always"
    command:
      - run
      - --hub.token=CHAVEAPITOKEN
      - --auth-server.advertise-url=http://hub-agent
      - --traefik.host=traefik
      - --traefik.tls.insecure=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - traefik

    depends_on:
      - traefik
  traefik:
    container_name: traefik
    restart: "always"
    image: "traefik:latest"
    command:
       # Habilitar HUB
      - --experimental.hub=true
      - --hub.tls.insecure=true
      - --metrics.prometheus.addrouterslabels=true


      # informa para o traefik como descobrir os containers
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443


      # informa para o traefik para não expor o container por padrão
      - --providers.docker.exposedbydefault=false

      - --api
      - --certificatesresolvers.letsencrypt.acme.email=EMAIL
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
    #  - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
    #  - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1
    #  - --certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0

      # configurar certificado coringa
     # - --entrypoints.websecure.http.tls=true
     # - --entrypoints.websecure.http.tls.certResolver=letsencrypt
     # - --entrypoints.websecure.http.tls.domains[0].main=DOMINIO
     # - --entrypoints.websecure.http.tls.domains[0].sans=*.DOMINIO



    # Configurar o traefik pilot
    #  - --pilot.token=TOKEN


     # - --log.level=DEBUG
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # Se for rodar via coomando substir linha abaixo por ./acme.json:/acme.json
      - "/opt/traefik/acme.json:/acme.json"
    labels:
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`DOMINIO`)"
      #- "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.entrypoints=websecure"

        # Configurar certificado coringa
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.domains[0].main=DOMINIO"
      - "traefik.http.routers.traefik.tls.domains[0].sans=*.DOMINIO"
      - "traefik.http.routers.traefik.service=api@internal"

      # Habilitar o traefik para expor o container
      - "traefik.enable=true"
      # Definir network do container para usar ip para expor
      - "traefik.docker.network=bridge"

      # Declaring the user list
      #
      # Note: when used in docker-compose.yml all dollar signs in the hash need to be doubled for escaping.
      # To create user:password pair, it's possible to use this command:
      # echo $(htpasswd -nB user) | sed -e s/\\$/\\$\\$/g
      #
      # Also note that dollar signs should NOT be doubled when they not evaluated (e.g. Ansible docker_container module).
      # Verificar traefikauth / traefik-https-chain
      - "traefik.http.middlewares.traefikauth.basicauth.users=USER"
      - "traefik.http.middlewares.traefik-https-chain.chain.middlewares=traefikauth"
      # linkar autentição do serviço traefik
      - "traefik.http.routers.traefik.middlewares=traefik-https-chain"


     #   Redirecionar todos para HTTPS
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

    environment:
      - CF_API_EMAIL=CF_API_EMAIL
      - CF_API_KEY=CF_API_KEY
    networks:
      - bridge
      - traefik

  traefik-certs-dumper:
    image: ldez/traefik-certs-dumper:v2.8.1
    entrypoint: sh -c '
      apk add jq
      ; while ! [ -e /acme.json ]
      || ! [ `jq ".[] | .Certificates | length" /acme.json` != 0 ]; do
      sleep 1
      ; done
      && traefik-certs-dumper file --version v2 --watch
      --source /acme.json --dest /data'
    volumes:
      - "/opt/traefik/acme.json:/acme.json"
      - "/opt/traefik/data:/data"


  webapp:
    image: containous/whoami
    container_name: "webapp"
    restart: "always"
    labels:
       #Habilitar o traefik para expor o container
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`DOMINIO`)"
      - "traefik.http.routers.webapp.entrypoints=websecure"
      - "traefik.http.routers.webapp.tls=true"
      - "traefik.http.routers.webapp.tls.certresolver=letsencrypt"

    networks:
      - traefik

