version: "3"

networks:
  traefik:
    name: traefik
    external: true

volumes:
  remotely-data:
      driver: local


services:
  remotely:
    restart: always
    image:  immybot/remotely
   # ports:
   #   - 5000:5000
    volumes:
      - remotely-data:/remotely-data
    labels:
      - "traefik.http.routers.remotely.rule=Host(`DOMINIO`)"
      - "traefik.http.routers.remotely.entrypoints=websecure"
      - "traefik.http.routers.remotely.tls=true"
      - "traefik.http.routers.remotely.tls.certresolver=letsencrypt"
      - "traefik.enable=true"

    networks:
      - traefik