version: "3"

networks:
  traefik:
    name: traefik
    external: true


services:
  dotnet:
    restart: always
    image: registry.gitlab.com/pedrostefanogv/dotnet_keycloak_auth:latest
   # ports:
   #   - 5000:5000

    labels:
      - "traefik.http.routers.dotnet.rule=Host(`DOMINIO`)"
      - "traefik.http.routers.dotnet.entrypoints=websecure"
      - "traefik.http.routers.dotnet.tls=true"
      - "traefik.http.routers.dotnet.tls.certresolver=letsencrypt"
      - "traefik.http.services.dotnet.loadbalancer.server.port=80"

      - "traefik.enable=true"

    networks:
      - traefik