version: "3"

networks:
  traefik:
    name: traefik
    external: true


services:
  remotely:
    restart: always
    image: registry.gitlab.com/pedrostefanogv/dotnet_keycloak_auth:latest
   # ports:
   #   - 5000:5000

    labels:
      - "traefik.http.routers.sped.rule=Host(`DOMINIO`)"
      - "traefik.http.routers.sped.entrypoints=websecure"
      - "traefik.http.routers.sped.tls=true"
      - "traefik.http.routers.sped.tls.certresolver=letsencrypt"
      - "traefik.enable=true"

    networks:
      - traefik