version: '3.7'

networks:
  traefik:
    name: traefik
    external: true


volumes:
  data1-1:
     name: data1-1
     driver: local
  data1-2:
     name: data1-2
     driver: local


services:
   minio1:
    restart: always
    image: quay.io/minio/minio
    container_name: minio
    command: server --console-address ":9000" http://minio/data{1...2}

    volumes:
      - data1-1:/data1
      - data1-2:/data2
    environment:
       MINIO_DOMAIN: minio.domain.com.br
       MINIO_SERVER_URL: https://minio.domain.com.br
       MINIO_ROOT_USER: minioadmin
       MINIO_ROOT_PASSWORD: minioadmin

    labels:
      - "traefik.http.routers.minio.rule=Host(`DOMINIO`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls=true"
      - "traefik.http.routers.minio.tls.certresolver=letsencrypt"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"

      - "traefik.enable=true"

    networks:
      - traefik






