version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      container_name: postgres
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: postgres-db
        POSTGRES_USER: user-postgres
        POSTGRES_PASSWORD: password-postgres

     # Para acessar externo descomentar abaixo
     # ports:
     #  - 5432:5432

      restart: always
      networks:
        - postgres-network

  pgadmin:
    container_name: postgres-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "EMAIL"
      PGADMIN_DEFAULT_PASSWORD: "PASSWORD"
    # ports:
    #  - "16543:80"

    restart: always

    depends_on:
      - postgres
    labels:
      # Configuração para acessar o pgadmin no navegador com traefik
      # Vide mais detalhes na configuração do traefik

      - "traefik.http.routers.pgadmin.rule=Host(`DOMINIO`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.routers.pgadmin.tls.certresolver=letsencrypt"

       # Habilitar traefik
      - --traefik.enable=true

    networks:
        - postgres-network
        - traefik
networks:

    # Rede interna para acesso ao banco de dados
    postgres-network:
    #   driver: none
